const input = document.getElementById('input')
const btn = document.getElementById('btn')
const output = document.getElementById('output')

let arrayWordsEnglish = ['of course', 'excuse me', 'welcome', 'nice', 'evening', 'day', 'morning', 'keys', 'where', 'honey', 'car', 'i need', 'table', 'tired', 'lot, much', 'want', 'here', 'sugar', 'very', 'cup', 'path', 'small', 'date', 'restaurant', 'eat, food', 'salad', 'today', 'cool', 'parents', 'pets', 'cat', 'dog', 'woman', 'enter', 'see', 'soccer', 'page', 'mom, mother', 'brother', 'dad, father', 'famous', 'family', 'teacher', 'wine', 'beer', 'but', 'thing', 'granddaughter', 'jacket', 'store', 'expensive', 'perfect', 'buy', 'birtday', 'best', 'friend', 'cheap', 'party', 'fun', 'song', 'so', 'interesting', 'coat', 'wallet', 'wife', 'bag', 'run', 'hand', 'talking (talk)', 'pants', 'now', 'near', 'sick', 'brown', 'warm', 'know', 'sit', 'together', 'write', 'speak', 'language', 'intelligent', 'tall', 'shoes', 'behind', 'station', 'driver', 'hospital', 'again', 'apartament', 'difficult', 'question', 'busy', 'really', 'easy', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'more', 'space', 'house', 'why', 'vegetarian', 'reading', 'meat', 'chicken', 'fries', 'vacation', 'clothes', 'dress', 'boot', 'hat', 'ready', 'gives (give)', 'reservation', 'glass', 'important', 'hungry', 'walk', 'happy', 'shows (show)', 'shirt', 'restroom', 'server', 'water', 'glass', 'would', 'soda', 'juice', 'beef', 'egg', 'meal', 'cheers!', 'joy (enjoy)', 'seek', 'cupcackes', 'plane', 'rock', 'bite', 'favorite', 'hot', 'got', 'cart', 'have', 'mall', 'fly (flying)', 'boring', 'shopping', 'beans', 'look', 'nervous', 'point', 'comming', 'drop', 'husband', 'hockey', 'jazz', 'safe', 'daughter', 'to cook', 'swim', 'ballet', 'sing', 'seat', 'sweet', 'son', 'hobby', 'chess', 'toe', 'chin', 'pin', 'ticket', 'desk', 'country', 'math', 'box', 'cute', 'always', 'forget', 'pink', 'then', 'over', 'ever', 'bees', 'beets', 'saw', 'learning', 'quickly', 'door', 'wait', 'leave', 'sometimes', 'mistake, eror', 'watch', 'still', 'room', 'than', 'newspaper', 'bench', 'band', 'bird', 'big', 'huge', 'hug', 'sheet', 'friendly', 'draw', 'throw', 'kick', 'ham', 'sleep', 'crazy', 'hole', 'hold', 'pass', 'past', 'bat', 'rain', 'spicy', 'rag', 'ring', 'married', 'miss', 'sent (send)', 'set', 'rarely', 'smart', 'lawyer', 'tar', 'hunter', 'smile', 'sense', 'humor', 'strange', 'breakfast', 'sink', 'dinner', 'lanch', 'bagel', 'teach', 'sweetheart', 'funny', 'handsome', 'lucky', 'many', 'lost', 'bathroom', 'nearby', 'there', 'dear', 'ATM', 'bus stop', 'straight', 'dean',
  'ahead', 'pharmacy', 'gift', 'breed', 'little', 'pit', 'kind', 'mend', 'pet', 'often', 'mind', 'switch', 'every', 'bell', 'beak', 'witch', 'ball', 'luck', 'alone', 'clean', 'pack', 'disadvantage', 'beat', 'bet', 'pad', 'side', 'fee', 'ugly', 'bid', 'fitting room', 'few', 'especialy', 'ride', 'sweater', 'tree', 'spot', 'rid', 'sale', 'long', 'too', 'tonight', 'hour', 'clock', 'free', 'sack', 'when', 'appointment', 'paint', 'what (how) about', 'done', 'tomorrow', 'later', 'see you', 'rush', 'laptop', 'lark', 'charge', 'ship', 'rust', 'flight', 'caryy-on', 'boarding', 'on time', 'mate', 'blank', 'sibling', 'skirt', 'might', 'blanket', 'skit', 'last name/ surname', 'bottle', 'bed', 'hone', 'pool', 'balcony', 'wonderful', 'term', 'excited', 'team', 'check out', 'cry', 'same', 'large', 'mate', 'dry', 'might', 'bridge', 'river', 'state', 'subway', 'crowded', 'treat', 'turn', 'burn', 'painting', 't-shirt', 'let', 'try', 'tray', 'major', 'university', 'become', 'bacause', 'class', 'strict', 'do', 'exam', 'genius', 'gender', 'soon', 'good luck', 'mouse', 'tender', 'moose', 'think', 'smoke', 'either', 'scary', 'get', 'meet', 'sad', 'feel', 'half', 'flower', 'plant', 'can', 'take', 'meeting', 'chair', 'enough', 'comfortable', 'join', 'orange', 'how much', 'pound', 'jam', 'whim', 'delicious', 'fresh', 'sell', 'train', 'solar', 'only', 'vegetables'  
]

console.log(arrayWordsEnglish.length)

function randomWords() {
  let words = Math.floor(Math.random() * arrayWordsEnglish.length)
  input.innerHTML = arrayWordsEnglish[words]
  return arrayWordsEnglish[words]
}

btn.addEventListener('click', randomWords)